begin;

insert into public.owor_hub_wave_config(warehouse, hub_code, wave_number, drop_order, active)
values
  ('CBT', 'PBT', 1, 1, true),
  ('CBT', 'BS9', 1, 2, true),
  ('CBT', 'BGS', 1, 1, true),
  ('CBT', 'BDC', 1, 2, true),
  ('CBT', 'CSA', 1, 1, true),
  ('CBT', 'SWL', 1, 2, true),
  ('CBT', 'SRP', 1, 1, true),
  ('CBT', 'JBG', 1, 2, true),
  ('CBT', 'PSG', 1, 1, true),
  ('CBT', 'CNR', 1, 2, true),
  ('CBT', 'CGS', 1, 1, true),
  ('CBT', 'MRG', 1, 2, true),
  ('CBT', 'DST', 1, 1, true),
  ('CBT', 'PGD', 1, 2, true),
  ('CBT', 'TAP', 1, 1, true),
  ('CBT', 'SLP', 1, 2, true),
  ('CBT', 'BSX', 1, 1, true),
  ('CBT', 'KLD', 1, 1, true),
  ('CBT', 'ASA', 1, 2, true),
  ('CBT', 'SAL', 2, 1, true),
  ('CBT', 'GMD', 2, 2, true),
  ('CBT', 'MRY', 2, 1, true),
  ('CBT', 'KGS', 2, 2, true),
  ('CBT', 'PPN', 2, 1, true),
  ('CBT', 'MTG', 2, 2, true),
  ('CBT', 'CWG', 2, 1, true),
  ('CBT', 'KLN', 2, 2, true),
  ('CBT', 'PLB', 2, 1, true),
  ('CBT', 'KPM', 2, 2, true),
  ('CBT', 'CT2', 2, 1, true),
  ('CBT', 'TGX', 2, 2, true),
  ('CBT', 'SWG', 2, 1, true),
  ('CBT', 'LIM', 2, 2, true),
  ('CBT', 'PPL', 2, 1, true),
  ('CBT', 'CLN', 2, 2, true),
  ('CBT', 'JLB', 3, 1, true),
  ('CBT', 'SMN', 3, 1, true),
  ('CBT', 'RDS', 3, 2, true),
  ('CBT', 'APR', 3, 1, true),
  ('CBT', 'BRY', 3, 2, true),
  ('CBT', 'PAM', 3, 1, true),
  ('CBT', 'PKC', 3, 2, true),
  ('CBT', 'LBB', 3, 1, true),
  ('CBT', 'MGR', 3, 2, true),
  ('CBT', 'GWB', 3, 1, true),
  ('CBT', 'FTW', 3, 1, true),
  ('CBT', 'CPT', 3, 2, true),
  ('CBT', 'TSY', 4, 1, true),
  ('CBT', 'HBD', 4, 1, true),
  ('CBT', 'JTI', 4, 1, true),
  ('CBT', 'PIN', 4, 1, true),
  ('CBT', 'BKJ', 4, 1, true),
  ('CBT', 'MSB', 4, 2, true),
  ('CBT', 'DNS', 4, 1, true),
  ('CBT', 'GPL', 4, 1, true),
  ('CBT', 'CAM', 4, 1, true),
  ('CBT', 'TDN', 4, 1, true),
  ('CBT', 'KJT', 4, 1, true)
on conflict (warehouse, hub_code) do update set
  wave_number = excluded.wave_number,
  drop_order = excluded.drop_order,
  active = excluded.active,
  updated_at = now();

commit;
